export const BiologyType = {
  OGTT_100G_1H_GLUCOSE_MMOL_L: { id: -1, name: '100g OGTT 1h Glucose (mmol/L)' },
  OGTT_100G_1H_GLUCOSE_MG_DL: { id: -2, name: '100g OGTT 1h Glucose (mg/dL)' },
  OGTT_100G_1H_GLUCOSE_G_L: { id: -3, name: '100g OGTT 1h Glucose (g/L)' },
  OGTT_100G_2H_GLUCOSE_MMOL_L: { id: -4, name: '100g OGTT 2h Glucose (mmol/L)' },
  OGTT_100G_2H_GLUCOSE_MG_DL: { id: -5, name: '100g OGTT 2h Glucose (mg/dL)' },
  OGTT_100G_2H_GLUCOSE_G_L: { id: -6, name: '100g OGTT 2h Glucose (g/L)' },
  OGTT_100G_FASTING_GLUCOSE_MMOL_L: { id: -7, name: '100g OGTT Fasting Glucose (mmol/L)' },
  OGTT_100G_FASTING_GLUCOSE_MG_DL: { id: -8, name: '100g OGTT Fasting Glucose (mg/dL)' },
  OGTT_100G_FASTING_GLUCOSE_G_L: { id: -9, name: '100g OGTT Fasting Glucose (g/L)' },
  HYDROXYPROGESTERONE_MG_L: { id: -10, name: '17-Hydroxyprogesterone (mg/L)' },
  HYDROXYPROGESTERONE_UMOL_L: { id: -11, name: '17-Hydroxyprogesterone (μmol/L)' },
  OGTT_50G_1H_GLUCOSE_MG_DL: { id: -12, name: '50g OGTT 1h Glucose (mg/dL)' },
  OGTT_50G_1H_GLUCOSE_G_L: { id: -13, name: '50g OGTT 1h Glucose (g/L)' },
  OGTT_50G_1H_GLUCOSE_MMOL_L: { id: -14, name: '50g OGTT 1h Glucose (mmol/L)' },
  OGTT_50G_FASTING_GLUCOSE_MMOL_L: { id: -15, name: '50g OGTT Fasting Glucose (mmol/L)' },
  OGTT_50G_FASTING_GLUCOSE_MG_DL: { id: -16, name: '50g OGTT Fasting Glucose (mg/dL)' },
  OGTT_50G_FASTING_GLUCOSE_G_L: { id: -17, name: '50g OGTT Fasting Glucose (g/L)' },
  OGTT_75G_1H_GLUCOSE_MMOL_L: { id: -18, name: '75g OGTT 1h Glucose (mmol/L)' },
  OGTT_75G_1H_GLUCOSE_MG_DL: { id: -19, name: '75g OGTT 1h Glucose (mg/dL)' },
  OGTT_75G_1H_GLUCOSE_G_L: { id: -20, name: '75g OGTT 1h Glucose (g/L)' },
  OGTT_75G_2H_GLUCOSE_MMOL_L: { id: -21, name: '75g OGTT 2h Glucose (mmol/L)' },
  OGTT_75G_2H_GLUCOSE_MG_DL: { id: -22, name: '75g OGTT 2h Glucose (mg/dL)' },
  OGTT_75G_2H_GLUCOSE_G_L: { id: -23, name: '75g OGTT 2h Glucose (g/L)' },
  OGTT_75G_FASTING_GLUCOSE_MMOL_L: { id: -24, name: '75g OGTT Fasting Glucose (mmol/L)' },
  OGTT_75G_FASTING_GLUCOSE_MG_DL: { id: -25, name: '75g OGTT Fasting Glucose (mg/dL)' },
  OGTT_75G_FASTING_GLUCOSE_G_L: { id: -26, name: '75g OGTT Fasting Glucose (g/L)' },
  ALANINE_AMINOTRANSFERASE_IU_L: { id: -27, name: 'Alanine Aminotransferase (IU/L)' },
  ALPHA_FETOPROTEIN_NG_ML: { id: -28, name: 'Alpha-Fetoprotein (ng/mL or μg/L)' },
  ANTI_MULLERIAN_HORMONE_PMOL_L: { id: -29, name: 'Anti-Müllerian Hormone (pmol/L)' },
  ANTI_MULLERIAN_HORMONE_NG_ML: { id: -30, name: 'Anti-Müllerian Hormone (ng/mL)' },
  ANTITHROMBIN_PERCENT: { id: -31, name: 'Antithrombin (%)' },
  ASPARTATE_AMINOTRANSFERASE_IU_L: { id: -32, name: 'Aspartate Aminotransferase (IU/L)' },
  BILIRUBIN_CONJUGATED_MG_DL: { id: -33, name: 'Bilirubin Conjugated/Direct (mg/dL)' },
  BILIRUBIN_CONJUGATED_UMOL_L: { id: -34, name: 'Bilirubin Conjugated/Direct (μmol/L)' },
  BILIRUBIN_TOTAL_MG_DL: { id: -35, name: 'Bilirubin Total (mg/dL)' },
  BILIRUBIN_TOTAL_UMOL_L: { id: -36, name: 'Bilirubin Total (μmol/L)' },
  CALCIUM_MMOL_L: { id: -37, name: 'Calcium (mmol/L)' },
  CHLORIDE_MMOL_L: { id: -38, name: 'Chloride (mmol/L or mEq/L)' },
  C_REACTIVE_PROTEIN_NMOL_L: { id: -39, name: 'C-Reactive Protein (nmol/L)' },
  C_REACTIVE_PROTEIN_MG_L: { id: -40, name: 'C-Reactive Protein (mg/L)' },
  CREATININE_UMOL_L: { id: -41, name: 'Creatinine (μmol/L)' },
  CREATININE_MG_DL: { id: -42, name: 'Creatinine (mg/dL)' },
  D_DIMERS_UG_L: { id: -43, name: 'D-Dimers (μg/L)' },
  DHEA_UG_DL: { id: -44, name: 'DHEA (μg/dL or pg/mL)' },
  DHEA_SULPHATE_UG_DL: { id: -45, name: 'DHEA Sulphate (μg/dL or pg/mL)' },
  FASTING_GLUCOSE_CONCENTRATION_MMOL_L: { id: -46, name: 'Fasting Glucose Concentration (mmol/L)' },
  FASTING_GLUCOSE_CONCENTRATION_MG_DL: { id: -47, name: 'Fasting Glucose Concentration (mg/dL)' },
  FASTING_GLUCOSE_CONCENTRATION_G_L: { id: -48, name: 'Fasting Glucose Concentration (g/L)' },
  FERRITIN_NG_ML: { id: -49, name: 'Ferritin (ng/mL or μg/L)' },
  FIBRINOGEN_G_L: { id: -50, name: 'Fibrinogen (g/L)' },
  FOLLICLE_STIMULATING_HORMONE_IU_L: { id: -51, name: 'Follicle Stimulating Hormone (IU/L)' },
  FREE_THYROXINE_PMOL_L: { id: -52, name: 'Free Thyroxine (pmol/L)' },
  FREE_THYROXINE_NG_DL: { id: -53, name: 'Free Thyroxine (ng/dL)' },
  GAMMA_GLUTAMYL_TRANSFERASE_U_L: { id: -54, name: 'Gamma-Glutamyl Transferase (U/L)' },
  GLYCATED_HAEMOGLOBIN_PERCENT: { id: -55, name: 'Glycated Haemoglobin (%)' },
  HDL_MMOL_L: { id: -56, name: 'HDL (mmol/L)' },
  HDL_MG_DL: { id: -57, name: 'HDL (mg/dL)' },
  HEMATOCRIT_PERCENT: { id: -58, name: 'Hematocrit (%)' },
  HEMOGLOBIN_G_L: { id: -59, name: 'Hemoglobin (g/L)' },
  HUMAN_CHORIONIC_GONADOTROPHIN_IU_L: { id: -60, name: 'Human Chorionic Gonadotrophin (IU/L or mU/mL)' },
  LDL_MMOL_L: { id: -61, name: 'LDL (mmol/L)' },
  LDL_MG_DL: { id: -62, name: 'LDL (mg/dL)' },
  LIPASE_U_L: { id: -63, name: 'Lipase (U/L)' },
  LUTEINISING_HORMONE_IU_L: { id: -64, name: 'Luteinising Hormone (IU/L)' },
  OESTRADIOL_PMOL_L: { id: -65, name: 'Oestradiol (pmol/L)' },
  OESTRADIOL_PG_ML: { id: -66, name: 'Oestradiol (pg/mL)' },
  PLATELET_PER_UL: { id: -67, name: 'Platelet (/μL)' },
  POTASSIUM_MMOL_L: { id: -68, name: 'Potassium (mmol/L or mEq/L)' },
  PROGESTERONE_NG_ML: { id: -69, name: 'Progesterone (ng/mL)' },
  PROGESTERONE_NMOL_L: { id: -70, name: 'Progesterone (nmol/L)' },
  PROLACTIN_UG_L: { id: -71, name: 'Prolactin (μg/L)' },
  PROLACTIN_MIU_L: { id: -72, name: 'Prolactin (mIU/L)' },
  PROTEIN_C_PERCENT: { id: -73, name: 'Protein C (%)' },
  PROTEIN_S_PERCENT: { id: -74, name: 'Protein S (%)' },
  PROTEINURIA_24H_MG_L: { id: -75, name: 'Proteinuria 24h (mg/L)' },
  PROTEINURIA_24H_MG_24H: { id: -76, name: 'Proteinuria 24h (mg/24h)' },
  PROTHROMBIN_TIME_PERCENT: { id: -77, name: 'Prothrombin Time (%)' },
  SODIUM_MMOL_L: { id: -78, name: 'Sodium (mmol/L or mEq/L)' },
  TESTOSTERONE_NMOL_L: { id: -79, name: 'Testosterone (nmol/L)' },
  TESTOSTERONE_NG_DL: { id: -80, name: 'Testosterone (ng/dL)' },
  THYROID_STIMULATING_HORMONE_MIU_L: { id: -81, name: 'Thyroid Stimulating Hormone (mIU/L or μIU/mL)' },
  TOTAL_CHOLESTEROL_MMOL_L: { id: -82, name: 'Total Cholesterol (mmol/L)' },
  TOTAL_CHOLESTEROL_MG_DL: { id: -83, name: 'Total Cholesterol (mg/dL)' },
  TRIGLYCERIDE_MMOL_L: { id: -84, name: 'Triglyceride (mmol/L)' },
  TRIGLYCERIDE_MG_DL: { id: -85, name: 'Triglyceride (mg/dL)' },
  UREA_MG_DL: { id: -86, name: 'Urea (mg/dL)' },
  UREA_MMOL_L: { id: -87, name: 'Urea (mmol/L)' },
  VITAMIN_D_NMOL_L: { id: -88, name: 'Vitamin D (nmol/L)' },
  VITAMIN_D_NG_ML: { id: -89, name: 'Vitamin D (ng/mL)' },
  WHITE_BLOOD_CELL_PER_MM3: { id: -90, name: 'White Blood Cell (/mm³ or /μL)' },
  URIC_ACID_UMOL_L: { id: -91, name: 'Uric Acid (μmol/L)' },
  URIC_ACID_MG_L: { id: -92, name: 'Uric Acid (mg/L)' },
  TCK_TCA: { id: -93, name: 'TCK/TCA' },
  B12_VITAMIN_PMOL_L: { id: -94, name: 'B12 Vitamin (pmol/L)' },
  B12_VITAMIN_NG_ML: { id: -95, name: 'B12 Vitamin (ng/mL)' }
} as const;

// Utility to get BiologyType by ID
export function getBiologyTypeById(id: number): typeof BiologyType[keyof typeof BiologyType] | undefined {
  return Object.values(BiologyType).find(type => type.id === id);
}

export const BiologyInterpretation = {
  NORMAL: { id: 1, name: 'Normal' },
  LOW: { id: 2, name: 'Low' },
  HIGH: { id: 3, name: 'High' }
} as const;

// Utility to get BiologyInterpretation by ID
export function getBiologyInterpretationById(id: number): typeof BiologyInterpretation[keyof typeof BiologyInterpretation] | undefined {
  return Object.values(BiologyInterpretation).find(interpretation => interpretation.id === id);
}